config/routes.rb
Huddle::Application.routes.draw do
  resources :status_reports

  resources :projects

  devise_for :users

  root :to => "welcome#index"

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :status_reports
  
  def reports_grouped_by_day
    status_reports.by_user_name.group_by(&:status_date)
  end
end

app/models/status_report.rb
class StatusReport < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
  
  # validations
  validate :validate_has_at_least_one_status
  def validate_has_at_least_one_status
    if today.blank? && yesterday.blank?
      errors[:base] << "Must have at least one status set"
    end
  end
  
  # named scopes
  scope :by_user_name, :include => "user", :order => "users.email ASC", :conditions => "user_id IS NOT NULL"
  
  before_save :set_status_date
  
  def set_status_date
    self.status_date = Date.today if status_date.nil?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!
  
  helper_method :current_project
  def current_project
    project = Project.find(session[:project_id]) rescue Project.last
  end
  
  def redirect_if_not_current_user(user_id)
    if user_id && user_id != current_user.id
      sign_out(current_user)
      redirect_to(new_user_session_path)
      return true
    end
    false
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.xml
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.xml
  def show
    @project = Project.find(params[:id])
    @reports = @project.reports_grouped_by_day

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.xml
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.xml
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to(@project, :notice => 'Project was successfully created.') }
        format.xml  { render :xml => @project, :status => :created, :location => @project }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.xml
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to(@project, :notice => 'Project was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.xml
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to(projects_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/status_reports_controller.rb
class StatusReportsController < ApplicationController
  # GET /status_reports
  # GET /status_reports.xml
  def index
    @status_reports = StatusReport.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @status_reports }
    end
  end

  # GET /status_reports/1
  # GET /status_reports/1.xml
  def show
    @status_report = StatusReport.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @status_report }
    end
  end

  # GET /status_reports/new
  # GET /status_reports/new.xml
  def new
    @status_report = StatusReport.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @status_report }
    end
  end

  # GET /status_reports/1/edit
  def edit
    @status_report = StatusReport.find(params[:id])
  end

  # POST /status_reports
  # POST /status_reports.xml
  def create
    return if redirect_if_not_current_user(params[:status_report][:user_id])
    
    params[:status_report].merge!(:user_id => current_user.id, :project_id => current_project.id)
    @status_report = StatusReport.new(params[:status_report])

    respond_to do |format|
      if @status_report.save
        format.html { redirect_to(@status_report, :notice => 'Status report was successfully created.') }
        format.xml  { render :xml => @status_report, :status => :created, :location => @status_report }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @status_report.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /status_reports/1
  # PUT /status_reports/1.xml
  def update
    @status_report = StatusReport.find(params[:id])

    respond_to do |format|
      if @status_report.update_attributes(params[:status_report])
        format.html { redirect_to(@status_report, :notice => 'Status report was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @status_report.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /status_reports/1
  # DELETE /status_reports/1.xml
  def destroy
    @status_report = StatusReport.find(params[:id])
    @status_report.destroy

    respond_to do |format|
      format.html { redirect_to(status_reports_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/status_reports_helper.rb
module StatusReportsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Huddle</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @projects.each do |project| %>
  <tr>
    <td><%= project.name %></td>
    <td><%= link_to 'Show', project %></td>
    <td><%= link_to 'Edit', edit_project_path(project) %></td>
    <td><%= link_to 'Destroy', project, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Status Reports for <%= @project.name %></h2>
<% @reports.keys.sort.each do |date| %>
	<div id="<%= date.to_s(:db) %>_day">
		<h3>Reports for <%= date.to_s(:long) %></h3>
		<% @reports[date].each do |report| %>
			<div id="<%= dom_id(report) %>">
				Yesterday I: <%= report.yesterday %>
				Today I will: <%= report.today %>
			</div>
		<% end # report loop filtered by date %>
	</div>
<% end # report date loop %>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/status_reports/_form.html.erb
<%= form_for(@status_report) do |f| %>
  <% if @status_report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status_report.errors.count, "error") %> prohibited this status_report from being saved:</h2>

      <ul>
      <% @status_report.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :yesterday %><br />
    <%= f.text_area :yesterday %>
  </div>
  <div class="field">
    <%= f.label :today %><br />
    <%= f.text_area :today %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/status_reports/edit.html.erb
<h1>Editing status_report</h1>

<%= render 'form' %>

<%= link_to 'Show', @status_report %> |
<%= link_to 'Back', status_reports_path %>

app/views/status_reports/index.html.erb
<h1>Listing status_reports</h1>

<table>
  <tr>
    <th>Project</th>
    <th>User</th>
    <th>Yesterday</th>
    <th>Today</th>
    <th>Status date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @status_reports.each do |status_report| %>
  <tr>
    <td><%= status_report.project %></td>
    <td><%= status_report.user %></td>
    <td><%= status_report.yesterday %></td>
    <td><%= status_report.today %></td>
    <td><%= status_report.status_date %></td>
    <td><%= link_to 'Show', status_report %></td>
    <td><%= link_to 'Edit', edit_status_report_path(status_report) %></td>
    <td><%= link_to 'Destroy', status_report, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Status report', new_status_report_path %>

app/views/status_reports/new.html.erb
<h1>New status_report</h1>

<%= render 'form' %>

<%= link_to 'Back', status_reports_path %>

app/views/status_reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Project:</b>
  <%= @status_report.project %>
</p>

<p>
  <b>User:</b>
  <%= @status_report.user %>
</p>

<p>
  <b>Yesterday:</b>
  <%= @status_report.yesterday %>
</p>

<p>
  <b>Today:</b>
  <%= @status_report.today %>
</p>

<p>
  <b>Status date:</b>
  <%= @status_report.status_date %>
</p>


<%= link_to 'Edit', edit_status_report_path(@status_report) %> |
<%= link_to 'Back', status_reports_path %>